"""
Curated equity universe for Meridian terminal.

Schema: (symbol, name, sector, industry, universe_group, seed_market_cap_b)
- universe_group: "S&P 500" | "Nasdaq 100" | "Dow 30" | "Growth" | "ETF" | "Crypto"
- seed_market_cap_b: rough market cap in USD billions (static, used as sort key
  and fallback; frontend overlays live prices from /api/market/quotes).

This is intentionally static so the terminal boots instantly and does not
depend on a live fundamentals feed. Names + sectors are stable enough that
maintenance is a once-a-year refresh task.
"""

UNIVERSE: list[tuple[str, str, str, str, str, float]] = [
    # --- Mega-cap technology ---
    ("AAPL", "Apple Inc.", "Information Technology", "Consumer Electronics", "S&P 500", 3400.0),
    ("MSFT", "Microsoft Corp.", "Information Technology", "Software", "S&P 500", 3200.0),
    ("NVDA", "NVIDIA Corp.", "Information Technology", "Semiconductors", "S&P 500", 3100.0),
    ("GOOGL", "Alphabet Inc. (A)", "Communication Services", "Interactive Media", "S&P 500", 2050.0),
    ("GOOG", "Alphabet Inc. (C)", "Communication Services", "Interactive Media", "S&P 500", 2050.0),
    ("AMZN", "Amazon.com Inc.", "Consumer Discretionary", "Internet Retail", "S&P 500", 2000.0),
    ("META", "Meta Platforms Inc.", "Communication Services", "Interactive Media", "S&P 500", 1400.0),
    ("TSLA", "Tesla Inc.", "Consumer Discretionary", "Auto Manufacturers", "S&P 500", 780.0),
    ("AVGO", "Broadcom Inc.", "Information Technology", "Semiconductors", "S&P 500", 820.0),
    ("ORCL", "Oracle Corp.", "Information Technology", "Software", "S&P 500", 380.0),
    ("CRM", "Salesforce Inc.", "Information Technology", "Software", "S&P 500", 295.0),
    ("ADBE", "Adobe Inc.", "Information Technology", "Software", "S&P 500", 230.0),
    ("CSCO", "Cisco Systems Inc.", "Information Technology", "Networking", "S&P 500", 205.0),
    ("ACN", "Accenture plc", "Information Technology", "IT Services", "S&P 500", 215.0),
    ("AMD", "Advanced Micro Devices", "Information Technology", "Semiconductors", "S&P 500", 260.0),
    ("QCOM", "Qualcomm Inc.", "Information Technology", "Semiconductors", "S&P 500", 195.0),
    ("TXN", "Texas Instruments", "Information Technology", "Semiconductors", "S&P 500", 175.0),
    ("INTC", "Intel Corp.", "Information Technology", "Semiconductors", "S&P 500", 140.0),
    ("IBM", "IBM", "Information Technology", "IT Services", "S&P 500", 215.0),
    ("INTU", "Intuit Inc.", "Information Technology", "Software", "S&P 500", 175.0),
    ("NOW", "ServiceNow Inc.", "Information Technology", "Software", "S&P 500", 205.0),
    ("AMAT", "Applied Materials", "Information Technology", "Semiconductor Equip.", "S&P 500", 170.0),
    ("LRCX", "Lam Research", "Information Technology", "Semiconductor Equip.", "S&P 500", 120.0),
    ("KLAC", "KLA Corp.", "Information Technology", "Semiconductor Equip.", "S&P 500", 100.0),
    ("MU", "Micron Technology", "Information Technology", "Semiconductors", "S&P 500", 130.0),
    ("PANW", "Palo Alto Networks", "Information Technology", "Cybersecurity", "S&P 500", 120.0),
    ("CRWD", "CrowdStrike Holdings", "Information Technology", "Cybersecurity", "S&P 500", 85.0),
    ("SNPS", "Synopsys Inc.", "Information Technology", "EDA Software", "S&P 500", 90.0),
    ("CDNS", "Cadence Design Systems", "Information Technology", "EDA Software", "S&P 500", 85.0),
    ("ADI", "Analog Devices", "Information Technology", "Semiconductors", "S&P 500", 110.0),
    ("MRVL", "Marvell Technology", "Information Technology", "Semiconductors", "S&P 500", 62.0),
    ("PLTR", "Palantir Technologies", "Information Technology", "Analytics Software", "S&P 500", 72.0),
    ("SNOW", "Snowflake Inc.", "Information Technology", "Software", "Growth", 52.0),
    ("DDOG", "Datadog Inc.", "Information Technology", "Software", "Growth", 42.0),
    ("NET", "Cloudflare Inc.", "Information Technology", "Edge Computing", "Growth", 32.0),
    ("ZS", "Zscaler Inc.", "Information Technology", "Cybersecurity", "Growth", 28.0),
    ("MDB", "MongoDB Inc.", "Information Technology", "Database", "Growth", 22.0),
    ("TEAM", "Atlassian Corp.", "Information Technology", "Software", "Growth", 55.0),
    ("WDAY", "Workday Inc.", "Information Technology", "Software", "S&P 500", 72.0),
    ("ANET", "Arista Networks", "Information Technology", "Networking", "S&P 500", 100.0),
    ("FTNT", "Fortinet Inc.", "Information Technology", "Cybersecurity", "S&P 500", 60.0),

    # --- Communications + Internet ---
    ("NFLX", "Netflix Inc.", "Communication Services", "Entertainment", "S&P 500", 280.0),
    ("DIS", "Walt Disney Co.", "Communication Services", "Entertainment", "S&P 500", 180.0),
    ("CMCSA", "Comcast Corp.", "Communication Services", "Media", "S&P 500", 155.0),
    ("T", "AT&T Inc.", "Communication Services", "Telecom", "S&P 500", 135.0),
    ("VZ", "Verizon Communications", "Communication Services", "Telecom", "S&P 500", 170.0),
    ("TMUS", "T-Mobile US", "Communication Services", "Wireless Telecom", "S&P 500", 195.0),
    ("SPOT", "Spotify Technology", "Communication Services", "Entertainment", "Growth", 80.0),
    ("SNAP", "Snap Inc.", "Communication Services", "Interactive Media", "Growth", 18.0),
    ("PINS", "Pinterest Inc.", "Communication Services", "Interactive Media", "Growth", 22.0),
    ("RBLX", "Roblox Corp.", "Communication Services", "Gaming", "Growth", 28.0),
    ("EA", "Electronic Arts", "Communication Services", "Gaming", "S&P 500", 38.0),
    ("TTWO", "Take-Two Interactive", "Communication Services", "Gaming", "S&P 500", 28.0),

    # --- Consumer Discretionary ---
    ("HD", "Home Depot", "Consumer Discretionary", "Home Improvement", "S&P 500", 385.0),
    ("LOW", "Lowe's Companies", "Consumer Discretionary", "Home Improvement", "S&P 500", 145.0),
    ("MCD", "McDonald's Corp.", "Consumer Discretionary", "Restaurants", "S&P 500", 210.0),
    ("SBUX", "Starbucks Corp.", "Consumer Discretionary", "Restaurants", "S&P 500", 110.0),
    ("NKE", "Nike Inc.", "Consumer Discretionary", "Apparel", "S&P 500", 120.0),
    ("LULU", "Lululemon Athletica", "Consumer Discretionary", "Apparel", "S&P 500", 42.0),
    ("TJX", "TJX Companies", "Consumer Discretionary", "Apparel Retail", "S&P 500", 135.0),
    ("BKNG", "Booking Holdings", "Consumer Discretionary", "Travel Services", "S&P 500", 135.0),
    ("ABNB", "Airbnb Inc.", "Consumer Discretionary", "Travel Services", "S&P 500", 90.0),
    ("UBER", "Uber Technologies", "Industrials", "Ground Transportation", "S&P 500", 165.0),
    ("LYFT", "Lyft Inc.", "Industrials", "Ground Transportation", "Growth", 7.5),
    ("DASH", "DoorDash Inc.", "Consumer Discretionary", "Internet Retail", "Growth", 55.0),
    ("CMG", "Chipotle Mexican Grill", "Consumer Discretionary", "Restaurants", "S&P 500", 88.0),
    ("F", "Ford Motor Co.", "Consumer Discretionary", "Auto Manufacturers", "S&P 500", 48.0),
    ("GM", "General Motors", "Consumer Discretionary", "Auto Manufacturers", "S&P 500", 52.0),
    ("RIVN", "Rivian Automotive", "Consumer Discretionary", "Auto Manufacturers", "Growth", 12.0),

    # --- Consumer Staples ---
    ("WMT", "Walmart Inc.", "Consumer Staples", "Discount Stores", "S&P 500", 520.0),
    ("COST", "Costco Wholesale", "Consumer Staples", "Discount Stores", "S&P 500", 380.0),
    ("PG", "Procter & Gamble", "Consumer Staples", "Household Products", "S&P 500", 385.0),
    ("KO", "Coca-Cola Co.", "Consumer Staples", "Beverages", "S&P 500", 275.0),
    ("PEP", "PepsiCo Inc.", "Consumer Staples", "Beverages", "S&P 500", 220.0),
    ("MDLZ", "Mondelez International", "Consumer Staples", "Packaged Foods", "S&P 500", 92.0),
    ("PM", "Philip Morris International", "Consumer Staples", "Tobacco", "S&P 500", 155.0),
    ("MO", "Altria Group", "Consumer Staples", "Tobacco", "S&P 500", 78.0),
    ("CL", "Colgate-Palmolive", "Consumer Staples", "Household Products", "S&P 500", 78.0),
    ("TGT", "Target Corp.", "Consumer Staples", "Discount Stores", "S&P 500", 70.0),
    ("KR", "Kroger Co.", "Consumer Staples", "Food Retail", "S&P 500", 42.0),

    # --- Healthcare ---
    ("LLY", "Eli Lilly & Co.", "Health Care", "Pharmaceuticals", "S&P 500", 720.0),
    ("UNH", "UnitedHealth Group", "Health Care", "Managed Care", "S&P 500", 480.0),
    ("JNJ", "Johnson & Johnson", "Health Care", "Pharmaceuticals", "S&P 500", 385.0),
    ("MRK", "Merck & Co.", "Health Care", "Pharmaceuticals", "S&P 500", 310.0),
    ("ABBV", "AbbVie Inc.", "Health Care", "Pharmaceuticals", "S&P 500", 310.0),
    ("PFE", "Pfizer Inc.", "Health Care", "Pharmaceuticals", "S&P 500", 160.0),
    ("TMO", "Thermo Fisher Scientific", "Health Care", "Life Sciences Tools", "S&P 500", 215.0),
    ("ABT", "Abbott Laboratories", "Health Care", "Medical Devices", "S&P 500", 195.0),
    ("DHR", "Danaher Corp.", "Health Care", "Life Sciences Tools", "S&P 500", 180.0),
    ("AMGN", "Amgen Inc.", "Health Care", "Biotechnology", "S&P 500", 160.0),
    ("BMY", "Bristol-Myers Squibb", "Health Care", "Pharmaceuticals", "S&P 500", 105.0),
    ("GILD", "Gilead Sciences", "Health Care", "Biotechnology", "S&P 500", 92.0),
    ("ISRG", "Intuitive Surgical", "Health Care", "Medical Devices", "S&P 500", 145.0),
    ("VRTX", "Vertex Pharmaceuticals", "Health Care", "Biotechnology", "S&P 500", 120.0),
    ("REGN", "Regeneron Pharmaceuticals", "Health Care", "Biotechnology", "S&P 500", 100.0),
    ("CVS", "CVS Health", "Health Care", "Healthcare Services", "S&P 500", 90.0),
    ("CI", "Cigna Group", "Health Care", "Managed Care", "S&P 500", 95.0),
    ("ELV", "Elevance Health", "Health Care", "Managed Care", "S&P 500", 120.0),
    ("HUM", "Humana Inc.", "Health Care", "Managed Care", "S&P 500", 42.0),
    ("MDT", "Medtronic plc", "Health Care", "Medical Devices", "S&P 500", 110.0),
    ("SYK", "Stryker Corp.", "Health Care", "Medical Devices", "S&P 500", 130.0),
    ("BSX", "Boston Scientific", "Health Care", "Medical Devices", "S&P 500", 120.0),
    ("MRNA", "Moderna Inc.", "Health Care", "Biotechnology", "S&P 500", 32.0),

    # --- Financials ---
    ("JPM", "JPMorgan Chase", "Financials", "Diversified Banks", "S&P 500", 620.0),
    ("BAC", "Bank of America", "Financials", "Diversified Banks", "S&P 500", 310.0),
    ("WFC", "Wells Fargo", "Financials", "Diversified Banks", "S&P 500", 200.0),
    ("C", "Citigroup Inc.", "Financials", "Diversified Banks", "S&P 500", 125.0),
    ("GS", "Goldman Sachs", "Financials", "Investment Banking", "S&P 500", 155.0),
    ("MS", "Morgan Stanley", "Financials", "Investment Banking", "S&P 500", 165.0),
    ("BLK", "BlackRock Inc.", "Financials", "Asset Management", "S&P 500", 140.0),
    ("SCHW", "Charles Schwab", "Financials", "Capital Markets", "S&P 500", 130.0),
    ("AXP", "American Express", "Financials", "Consumer Finance", "S&P 500", 180.0),
    ("V", "Visa Inc.", "Financials", "Transaction Processing", "S&P 500", 545.0),
    ("MA", "Mastercard Inc.", "Financials", "Transaction Processing", "S&P 500", 440.0),
    ("PYPL", "PayPal Holdings", "Financials", "Transaction Processing", "S&P 500", 72.0),
    ("SQ", "Block Inc.", "Financials", "Transaction Processing", "Growth", 48.0),
    ("COIN", "Coinbase Global", "Financials", "Capital Markets", "Growth", 62.0),
    ("HOOD", "Robinhood Markets", "Financials", "Capital Markets", "Growth", 18.0),
    ("BRK-B", "Berkshire Hathaway (B)", "Financials", "Multi-Line Insurance", "S&P 500", 880.0),
    ("SPGI", "S&P Global", "Financials", "Financial Data", "S&P 500", 145.0),
    ("MCO", "Moody's Corp.", "Financials", "Financial Data", "S&P 500", 82.0),
    ("ICE", "Intercontinental Exchange", "Financials", "Exchanges", "S&P 500", 80.0),
    ("CME", "CME Group", "Financials", "Exchanges", "S&P 500", 75.0),
    ("AIG", "American International Group", "Financials", "Insurance", "S&P 500", 52.0),
    ("PGR", "Progressive Corp.", "Financials", "Insurance", "S&P 500", 115.0),
    ("TRV", "Travelers Companies", "Financials", "Insurance", "S&P 500", 52.0),

    # --- Industrials ---
    ("BA", "Boeing Co.", "Industrials", "Aerospace & Defense", "S&P 500", 110.0),
    ("CAT", "Caterpillar Inc.", "Industrials", "Machinery", "S&P 500", 175.0),
    ("DE", "Deere & Co.", "Industrials", "Machinery", "S&P 500", 115.0),
    ("GE", "GE Aerospace", "Industrials", "Aerospace & Defense", "S&P 500", 175.0),
    ("HON", "Honeywell International", "Industrials", "Industrial Conglomerates", "S&P 500", 135.0),
    ("LMT", "Lockheed Martin", "Industrials", "Aerospace & Defense", "S&P 500", 115.0),
    ("RTX", "RTX Corp.", "Industrials", "Aerospace & Defense", "S&P 500", 135.0),
    ("NOC", "Northrop Grumman", "Industrials", "Aerospace & Defense", "S&P 500", 70.0),
    ("UPS", "United Parcel Service", "Industrials", "Air Freight & Logistics", "S&P 500", 115.0),
    ("FDX", "FedEx Corp.", "Industrials", "Air Freight & Logistics", "S&P 500", 70.0),
    ("UNP", "Union Pacific", "Industrials", "Rail Transportation", "S&P 500", 150.0),
    ("CSX", "CSX Corp.", "Industrials", "Rail Transportation", "S&P 500", 68.0),
    ("MMM", "3M Co.", "Industrials", "Industrial Conglomerates", "S&P 500", 55.0),
    ("ETN", "Eaton Corp. plc", "Industrials", "Electrical Components", "S&P 500", 125.0),
    ("EMR", "Emerson Electric", "Industrials", "Electrical Components", "S&P 500", 62.0),
    ("WM", "Waste Management", "Industrials", "Environmental Services", "S&P 500", 80.0),
    ("PH", "Parker-Hannifin", "Industrials", "Machinery", "S&P 500", 72.0),

    # --- Energy ---
    ("XOM", "Exxon Mobil Corp.", "Energy", "Integrated Oil & Gas", "S&P 500", 465.0),
    ("CVX", "Chevron Corp.", "Energy", "Integrated Oil & Gas", "S&P 500", 280.0),
    ("COP", "ConocoPhillips", "Energy", "Oil & Gas E&P", "S&P 500", 135.0),
    ("EOG", "EOG Resources", "Energy", "Oil & Gas E&P", "S&P 500", 75.0),
    ("PSX", "Phillips 66", "Energy", "Oil & Gas Refining", "S&P 500", 60.0),
    ("MPC", "Marathon Petroleum", "Energy", "Oil & Gas Refining", "S&P 500", 62.0),
    ("VLO", "Valero Energy", "Energy", "Oil & Gas Refining", "S&P 500", 50.0),
    ("SLB", "Schlumberger", "Energy", "Oil & Gas Equipment", "S&P 500", 62.0),
    ("OXY", "Occidental Petroleum", "Energy", "Oil & Gas E&P", "S&P 500", 58.0),

    # --- Materials / Utilities / Real Estate ---
    ("LIN", "Linde plc", "Materials", "Industrial Gases", "S&P 500", 215.0),
    ("SHW", "Sherwin-Williams", "Materials", "Specialty Chemicals", "S&P 500", 85.0),
    ("APD", "Air Products & Chemicals", "Materials", "Industrial Gases", "S&P 500", 60.0),
    ("FCX", "Freeport-McMoRan", "Materials", "Copper", "S&P 500", 68.0),
    ("NEM", "Newmont Corp.", "Materials", "Gold", "S&P 500", 45.0),
    ("NEE", "NextEra Energy", "Utilities", "Electric Utilities", "S&P 500", 150.0),
    ("SO", "Southern Co.", "Utilities", "Electric Utilities", "S&P 500", 82.0),
    ("DUK", "Duke Energy", "Utilities", "Electric Utilities", "S&P 500", 78.0),
    ("AMT", "American Tower", "Real Estate", "Specialized REIT", "S&P 500", 95.0),
    ("PLD", "Prologis Inc.", "Real Estate", "Industrial REIT", "S&P 500", 110.0),
    ("EQIX", "Equinix Inc.", "Real Estate", "Specialized REIT", "S&P 500", 75.0),
    ("O", "Realty Income", "Real Estate", "Retail REIT", "S&P 500", 48.0),
    ("SPG", "Simon Property Group", "Real Estate", "Retail REIT", "S&P 500", 52.0),
    ("CCI", "Crown Castle", "Real Estate", "Specialized REIT", "S&P 500", 42.0),

    # --- ETFs ---
    ("SPY", "SPDR S&P 500 ETF", "ETF", "Large Cap Blend", "ETF", 0),
    ("QQQ", "Invesco QQQ Trust", "ETF", "Large Cap Growth", "ETF", 0),
    ("IWM", "iShares Russell 2000", "ETF", "Small Cap Blend", "ETF", 0),
    ("DIA", "SPDR Dow Jones", "ETF", "Large Cap Value", "ETF", 0),
    ("VTI", "Vanguard Total Stock", "ETF", "Total Market", "ETF", 0),
    ("VOO", "Vanguard S&P 500", "ETF", "Large Cap Blend", "ETF", 0),
    ("VEA", "Vanguard Developed Markets", "ETF", "International", "ETF", 0),
    ("VWO", "Vanguard Emerging Markets", "ETF", "Emerging Markets", "ETF", 0),
    ("EEM", "iShares MSCI Emerging", "ETF", "Emerging Markets", "ETF", 0),
    ("EFA", "iShares MSCI EAFE", "ETF", "International", "ETF", 0),
    ("TLT", "iShares 20+ Yr Treasury", "ETF", "Long Duration", "ETF", 0),
    ("IEF", "iShares 7-10 Yr Treasury", "ETF", "Intermediate Duration", "ETF", 0),
    ("SHY", "iShares 1-3 Yr Treasury", "ETF", "Short Duration", "ETF", 0),
    ("HYG", "iShares High Yield Corp", "ETF", "High Yield Bond", "ETF", 0),
    ("LQD", "iShares Inv Grade Corp", "ETF", "Investment Grade Bond", "ETF", 0),
    ("GLD", "SPDR Gold Shares", "ETF", "Gold", "ETF", 0),
    ("SLV", "iShares Silver Trust", "ETF", "Silver", "ETF", 0),
    ("USO", "US Oil Fund", "ETF", "Oil", "ETF", 0),
    ("UNG", "US Natural Gas Fund", "ETF", "Natural Gas", "ETF", 0),
    ("XLK", "Technology Select SPDR", "ETF", "Technology Sector", "ETF", 0),
    ("XLF", "Financial Select SPDR", "ETF", "Financial Sector", "ETF", 0),
    ("XLE", "Energy Select SPDR", "ETF", "Energy Sector", "ETF", 0),
    ("XLV", "Health Care Select SPDR", "ETF", "Health Care Sector", "ETF", 0),
    ("XLI", "Industrial Select SPDR", "ETF", "Industrial Sector", "ETF", 0),
    ("XLY", "Cons Disc Select SPDR", "ETF", "Consumer Disc Sector", "ETF", 0),
    ("XLP", "Cons Staples Select SPDR", "ETF", "Consumer Stap Sector", "ETF", 0),
    ("XLU", "Utilities Select SPDR", "ETF", "Utilities Sector", "ETF", 0),
    ("XLRE", "Real Estate Select SPDR", "ETF", "Real Estate Sector", "ETF", 0),
    ("XLB", "Materials Select SPDR", "ETF", "Materials Sector", "ETF", 0),
    ("XLC", "Comm Services SPDR", "ETF", "Comm Services Sector", "ETF", 0),
    ("SMH", "VanEck Semiconductor", "ETF", "Semiconductors", "ETF", 0),
    ("SOXX", "iShares Semiconductor", "ETF", "Semiconductors", "ETF", 0),
    ("ARKK", "ARK Innovation", "ETF", "Disruptive Growth", "ETF", 0),
    ("VNQ", "Vanguard Real Estate", "ETF", "Real Estate", "ETF", 0),
    ("VIG", "Vanguard Dividend Apprec", "ETF", "Dividend Growth", "ETF", 0),
    ("SCHD", "Schwab US Dividend", "ETF", "Dividend Equity", "ETF", 0),
    ("VXX", "iPath VIX Short-Term", "ETF", "Volatility", "ETF", 0),
    ("UVXY", "ProShares Ultra VIX", "ETF", "Leveraged Volatility", "ETF", 0),

    # --- Crypto ---
    ("BTC-USD", "Bitcoin", "Cryptocurrency", "Large Cap Crypto", "Crypto", 1350.0),
    ("ETH-USD", "Ethereum", "Cryptocurrency", "Large Cap Crypto", "Crypto", 410.0),
    ("SOL-USD", "Solana", "Cryptocurrency", "Large Cap Crypto", "Crypto", 92.0),
    ("BNB-USD", "BNB", "Cryptocurrency", "Large Cap Crypto", "Crypto", 85.0),
    ("XRP-USD", "XRP", "Cryptocurrency", "Large Cap Crypto", "Crypto", 35.0),
    ("ADA-USD", "Cardano", "Cryptocurrency", "Large Cap Crypto", "Crypto", 18.0),
    ("DOGE-USD", "Dogecoin", "Cryptocurrency", "Memecoin", "Crypto", 22.0),
    ("AVAX-USD", "Avalanche", "Cryptocurrency", "Large Cap Crypto", "Crypto", 13.0),
    ("DOT-USD", "Polkadot", "Cryptocurrency", "Large Cap Crypto", "Crypto", 11.0),
    ("MATIC-USD", "Polygon", "Cryptocurrency", "Large Cap Crypto", "Crypto", 9.0),
    ("LINK-USD", "Chainlink", "Cryptocurrency", "Oracle Network", "Crypto", 8.5),
]


def build_universe_payload() -> list[dict]:
    """Serialize the universe as a list of dicts ready for JSON."""
    return [
        {
            "symbol": symbol,
            "name": name,
            "sector": sector,
            "industry": industry,
            "universe": group,
            "marketCapB": market_cap,
        }
        for (symbol, name, sector, industry, group, market_cap) in UNIVERSE
    ]


def universe_symbols() -> list[str]:
    return [row[0] for row in UNIVERSE]
